#!/bin/sh

# :^)
eval "$(sed -e '/^thirdparty_jail=/s/=.*/=off/' \
            -e '\@/var/luna/preferences/devmode_enabled@s/if /&false \&\& /' \
            -e '/inspect-port/s/127\.0\.0\.1/0.0.0.0/' \
            '/usr/bin/run-js-service')"
