#!/bin/sh

# NODE_OPTIONS is only supported by node v8.0.0 (so webOS 5+)
export NODE_OPTIONS='--use-openssl-ca'

# :^)
eval "$(sed -e '/^thirdparty_jail=/s/=.*/=off/' \
            -e '\@/var/luna/preferences/devmode_enabled@s/if /&false \&\& /' \
            '/usr/bin/run-js-service')"
