name: Build & Release

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - run: npm ci
    - run: npm run build -- --production
    - run: npm run build-service -- --env production
    - run: npm run package
    - run: npm run manifest

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload Release assets
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ steps.get_release.outputs.tag_name }}
        allowUpdates: true
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
        omitPrereleaseDuringUpdate: true
        artifacts: '*.ipk,org.webosbrew.hbchannel.manifest.json'
