name: 'Build & Release'

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run build -- --production
    - run: npm run build-service -- --env production
    - run: npm run package
    - run: npm run manifest

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@74c3d60f5a28f358ccf241a00c9021ea16f0569f
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload IPK
      uses: ncipollo/release-action@v1
      with:
        name: Release ${{ steps.get_release.outputs.tag_name }}
        allowUpdates: true
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
        omitDraftDuringUpdate: true
        omitPrereleaseDuringUpdate: true
        artifacts: '*.ipk,*.manifest.json'
